version: '3.8'
services:
  web:
    build:
      context: apache/
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    networks:
      - overlay
    links:
      - db
    tty: true
    stdin_open: true

  db:
    build:
      context: postgres/
    ports:
      - "5433:5432"
    networks:
      - overlay
    environment:
      PG_PASSWORD: q1w2e3r4
      POSTGRES_USER: iriusprod
      POSTGRES_PASSWORD: iriusprod
      POSTGRES_DB: iriusprod


networks:
  overlay: